<?php
    // set the required headers
    header("Access-Control-Allow-Origin: https://wegivesupport.net/");      //
    header('Access-Control-Allow-Methods: GET, POST');                      // allow only POST http method   
    

    // include the needed config files
    include_once '../config/database.php';
    include_once '../objects/agent.php';
    include_once '../help/opsupport.php';

    /************************************ NOTICE ************************************
    the salt is randomically generated by two functions:
    random_bytes($lenght) for generate a $lenght (12) random bytes string
    bin2hex to encode the previosly bytes string in hex string
    the password is generate by password_hash function which give
    in input the salt and password (clear) and hashing the composed
    string with blowfish algorithm
    ********************************************************************************/

    //function for the attempt authentication
    function attemptAuth(){
        // fetch all HTTP headers received from client
        $allHeaders = getallheaders();
        // check if is present the authentication
        if(!isset($allHeaders['Authorization']))
            return false;
        else
        {
            // ...and if it's Basic            
            if(!OpSupport::startsWith(($allHeaders['Authorization']),'Basic'))
                return false;
        }
        // extract the Basic Authentication base64 encoded string
        $encodedString = substr($allHeaders['Authorization'], 6);
        // decode the string
        $decodedString = base64_decode($encodedString);
        // separate username and password for next controls
        $credentials = explode(':', $decodedString);

        // get database connection
        $database = new Database();
        $db = $database->getConnection();

        // instantiate new agent object for login checking
        $agent = new Agent($db);
        $agent->username = $credentials[0];

        $isUsername = $agent->usernameExists();
        if($isUsername)
            // set response code
            http_response_code(200);
        else
            // set response code
            http_response_code(401);
    }

    attemptAuth();
?>